# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

output: prefixed

dotenv:
  - .env

vars:
  GREETING: Hello, world!

tasks:
  default:
    cmds:
      - task --list
    silent: true

  dev:
    desc: Start dev environtment
    deps:
      - dev:backend
      - dev:frontend

  dev:backend:
    desc: Run Go backend with live reload (or go run)
    dir: backend
    cmd: air

  dev:frontend:
    desc: "Run React dev server"
    dir: frontend
    cmds:
      - bun run dev
  gen:openapi:
    desc: "Generate OpenAPI client for frontend"
    dir: frontend
    cmds:
      - bun run openapi-ts

  check:
    desc: "Check code"
    dir: frontend
    cmds:
      - bun run check

  check:fix:
    desc: "Fix code"
    dir: frontend
    cmds:
      - bun run check --fix
