# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

output: prefixed

dotenv:
  - .env

vars:
  GREETING: Hello, world!

tasks:
  default:
    cmds:
      - task --list
    silent: true
  dev:
    desc: Start dev environtment
    watch: true
    deps:
      - dev:backend
      - dev:frontend

  dev:backend:
    desc: Run Go backend with live reload (or go run)
    dir: backend
    watch: true
    cmd: air

  dev:frontend:
    desc: "Run React dev server"
    dir: frontend
    watch: true
    cmds:
      - bun run dev

  check:
    desc: "Check code"
    dir: frontend
    cmds:
      - bun run check

  check:env:
    desc: Verify environment variables directly from Task
    cmds:
      - echo "PUBLIC_APP_URL is -> [${PUBLIC_APP_URL}]"
