/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedExplorerIndexRouteImport } from './routes/_protected/explorer/index'
import { Route as ProtectedExplorerSourceIdIndexRouteImport } from './routes/_protected/explorer/$sourceId/index'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedExplorerIndexRoute = ProtectedExplorerIndexRouteImport.update({
  id: '/explorer/',
  path: '/explorer/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedExplorerSourceIdIndexRoute = ProtectedExplorerSourceIdIndexRouteImport.update({
  id: '/explorer/$sourceId/',
  path: '/explorer/$sourceId/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/explorer/': typeof ProtectedExplorerIndexRoute
  '/explorer/$sourceId/': typeof ProtectedExplorerSourceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/explorer': typeof ProtectedExplorerIndexRoute
  '/explorer/$sourceId': typeof ProtectedExplorerSourceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/explorer/': typeof ProtectedExplorerIndexRoute
  '/_protected/explorer/$sourceId/': typeof ProtectedExplorerSourceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/explorer/' | '/explorer/$sourceId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/explorer' | '/explorer/$sourceId'
  id:
    | '__root__'
    | '/_protected'
    | '/_protected/'
    | '/_protected/explorer/'
    | '/_protected/explorer/$sourceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/explorer/': {
      id: '/_protected/explorer/'
      path: '/explorer'
      fullPath: '/explorer/'
      preLoaderRoute: typeof ProtectedExplorerIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/explorer/$sourceId/': {
      id: '/_protected/explorer/$sourceId/'
      path: '/explorer/$sourceId'
      fullPath: '/explorer/$sourceId/'
      preLoaderRoute: typeof ProtectedExplorerSourceIdIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedExplorerIndexRoute: typeof ProtectedExplorerIndexRoute
  ProtectedExplorerSourceIdIndexRoute: typeof ProtectedExplorerSourceIdIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedExplorerIndexRoute: ProtectedExplorerIndexRoute,
  ProtectedExplorerSourceIdIndexRoute: ProtectedExplorerSourceIdIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
